### ISSUE TITLE
Exception in Script Error

### ISSUE THREAD

**Issue by sjaustad** [jdanders/ksl-classifieds-notifier#4]
Recently two weeks ago I started getting sent emails with the title "Exception in script detected."  The script seems to work correctly otherwise, so I still get all of the notifications I would expect, but I get a lot of these emails too.  Today I got 68 of these emails all within 20 minutes of each other.  I'm running several simultaneous searches on the same computer, so all of my search queries are generating this error.  Here is a sample of the message contents.  

New match found for query Exception in script detected.
Exception count 11
The script will die after the count reaches 10
HTTP Error 403: Forbidden
['34', '1440p']

New match found for query Exception in script detected.
Exception count 10
The script will die after the count reaches 10
HTTP Error 403: Forbidden
['1080 ti']

Let me know if I can get you more information.
Thanks

**Comment by jdanders** [comment]
Those errors are the response code from ksl.com. Presumably if you visited KSL at the same time the script got one of those responses, your browser would say the same thing. 

I haven't been running any searches lately so I started one when I saw this issue. I haven't seen any exception emails yet. Have you seen some since posting the issue? Have you changed the time between checking from the default of 10 minutes? 

One of the side effects of this script is that you get to find out KSL's uptime. Turns out they have some bad spells.

**Comment by sjaustad** [comment]
Yes, I'm running them in a 5 minute interval, I was wondering if that might be causing the issue. I did get some exceptions through the night. Let me try my searches at the default 10 and see if I don't get anymore.
UPDATE:  Even after moving all of my searches to the default interval, I still got a couple of Exceptions in the past few hours.

**Comment by jdanders** [comment]
I changed the default behavior to only send exceptions through email after 5 have happened in a row. It will continue to email until 10 exceptions happen. After 10 it will quit. The threshold of 5 is configurable, but I don't think anyone would really want to change it, except maybe up to 9 or something...
Fixed in commit 00b6cb7
