### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by jdcargile** [jdanders/ksl-classifieds-notifier#7]
What value are you guys getting out of using this tool that the new Run Search and Alerts built into KSL Classifieds doesn't do?

I ask because I want to understand the use case. I've wanted to contribute to this repo, but between the new Alerts and Home customization options, I'm curious how you guys/others might be using it.

**Comment by jdanders** [comment]
This project was created before that feature existed, so it filled that need originally. I haven't actually hunted on KSL for a while, but I'd imagine the Alerts that are now available would fill the same role.

One advantage is that this is self-hosted and doesn't require creating an account on KSL, but that's a pretty slight advantage that only the most hardcore of privacy nuts would benefit from.

Also, there may be a response time difference. If the KSL Alert delays the notification then that would be a disadvantage when searching for high-demand items. But since I haven't used Alerts yet, I don't know if that's actually the case.

**Comment by jdcargile** [comment]
Thank you for the response. 👍 

You should check out Alerts. They work really well and you can set up them to be sent Immediately or even get a daily or weekly digest. I'm not fond of the amount of ads and stuff that they serve up still. I occasionally check their system to see if they've migrated from embedded javascript on the page to actually using an API. The moment they change out their technology stack, we can all rejoice and json via rest services and stop parsing html. 😄 

In the meantime, I will check out your repo again and check out the new features you have added. Thanks for what you've done.
